apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::528475072171:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1E24J07VWDHNB
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::528475072171:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-24T01:28:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "838"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 7f9aef90-1246-49fe-8737-6172b61b95ff
